---
- name: Configuring vsftpd
  template:
    src: "vsftpd.conf.j2"
    dest: "{{ vsftpd_config_template_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart vsftpd

- name: Anon upload folder
  file:
    path: "{{ anon_upload }}"
    state: directory
    owner: ftp
    group: ftp

- name: Setup SeLinux options
  seboolean:
    name: "{{ item.option }}"
    state: "{{ item.state }}"
  loop: "{{ selinux_options }}"

