---
- name: Includeing OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: install.yml
- import_tasks: config.yml
- import_tasks: config_firewall.yml
- import_tasks: service.yml
